/* ////////////////////////////////////////////////////////////////////////////
			          MainForm.cs
///////////////////////////////////////////////////////////////////////////////
DESCRIPTION:	Here's where we'll keep boilerplate code and event handlers
		generated by Visual Studio.

REVISIONS:	 5 Aug 16 - RAC - Adapted from an earlier version
//////////////////////////////////////////////////////////////////////////// */

using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Text;
using System.Threading;
using System.Windows.Forms;

namespace waedit
{
public partial class MainForm : Form
{

/* ////////////////////////////////////////////////////////////////////////////
				     Data
//////////////////////////////////////////////////////////////////////////// */

Text		text = new Text();	// The main text buffer
Thread		mainLoopThread;		// The main editor loop
public string	currentFilename;	// Name of the file being edited
int		currentChar;		// Current position within text buffer

/* ////////////////////////////////////////////////////////////////////////////
				  MainForm()
///////////////////////////////////////////////////////////////////////////////
DESCRIPTION:	The MainForm constructor.  Boilerplate generated by Visual
		Studio.

REVISIONS:	 5 Aug 16 - RAC - Genesis
		18 Sep 25 - RAC - Wired up mouse wheel handler
//////////////////////////////////////////////////////////////////////////// */

public MainForm()
{
    InitializeComponent();
    editorPanel.MouseWheel += editorPanel_MouseWheel;
    statusStrip.AutoSize = false;
    this.MinimumSize = new Size(300, 300);   // width, height
}

/* ////////////////////////////////////////////////////////////////////////////
			      MainForm_KeyPress()
			      MainForm_KeyDown()
///////////////////////////////////////////////////////////////////////////////
DESCRIPTION:	The framework calls KeyPress() for normal keys that produce
                printable characters.  We queue them up for processing by the
                editor.

		We use KeyDown() to handle special keys (the arrows, Home, Del,
		etc.) that don't produce printable characters.  Here we
		translate their key codes into codes that don't collide with
		the normal printable characters before adding them to the
		input queue.

REVISIONS:	27 Jul 16 - RAC - Genesis, in a preliminary test program
		 3 Aug 16 - RAC - Ported to here
//////////////////////////////////////////////////////////////////////////// */

private void MainForm_KeyPress(object sender, KeyPressEventArgs e)
{
    QueueKey((byte)e.KeyChar);
}						// End Form1_KeyPress

/* ///////////////////////////////////////////////////////////////////////// */

private void MainForm_KeyDown(object sender, KeyEventArgs e)
{
    switch (e.KeyCode)
    {
	case Keys.PageUp:	QueueKey(C.PGUP);	break;
	case Keys.PageDown:	QueueKey(C.PGDN);	break;
	case Keys.Home:		QueueKey(C.HOME);	break;
	case Keys.Left:		QueueKey(C.LEFT);	break;
	case Keys.Up:		QueueKey(C.UP);		break;
	case Keys.Right:	QueueKey(C.RIGHT);	break;
	case Keys.Down:		QueueKey(C.DOWN);	break;
	case Keys.Delete:	QueueKey(C.DELETE);	break;
#if DEBUG
        case Keys.F1:		QueueKey(C.F1);		break;
#endif
    }						// End switch
}

/* ////////////////////////////////////////////////////////////////////////////
				 Initialize()
///////////////////////////////////////////////////////////////////////////////
DESCRIPTION:    Call this function to set up the editor with an empty buffer.
                This is an excellent idea when the program first starts up, and
                also before loading a new file.

REVISIONS:	22 Aug 16 - RAC - Genesis
//////////////////////////////////////////////////////////////////////////// */

void Initialize()
{
    currentChar = 0;
    cursorX = 0;
    currentLine = 0;
    ClearSelection();
    text.Initialize();
}						// End Initialize()

/* ////////////////////////////////////////////////////////////////////////////
			       MainForm_Load()
///////////////////////////////////////////////////////////////////////////////
DESCRIPTION:	The framework calls this function at startup before the form is
		loaded.  We us it to perform various initialization chores.

REVISIONS:	 1 Aug 16 - RAC - Skeleton
		 3 Aug 16 - RAC - Added call to invoke the executor thread
		22 Aug 16 - RAC - Added logic to load the input file
		 1 Sep 16 - RAC - Added logic to restore the form's size and
		 		   position at startup
//////////////////////////////////////////////////////////////////////////// */

private void MainForm_Load(object sender, EventArgs e)
{
    string	s;
    string	startupMacroFilename;

    this.WindowState = Properties.Settings.Default.MainFormState;
    this.Location    = Properties.Settings.Default.MainFormLocation;
    this.Size	     = Properties.Settings.Default.MainFormSize;
    if (this.WindowState == FormWindowState.Minimized)
    {
	this.WindowState = FormWindowState.Normal;
    }

    Initialize();				// Go set up for a new file

    if (File.Exists(currentFilename))		// If input filename was given
    {
	s = File.ReadAllText(currentFilename);	// Read it
	s = s.Replace (				// Fix up EOLs
	    DetectLineDelimiter(s), "\r");		
        text.InsertBlock(currentChar,		// Convert to List<byte> and
	    new List<byte> (			//  dump in the text buffer
	    Encoding.ASCII.GetBytes(s)));
    }						// End 'input file exists'
    text.NoUnsavedChangesYet();			// No changes to buffer yet
    TakeUndoSnapshot(0);			// Take initial undo snapshot    

    UpdateFont();

    mainLoopThread = new Thread (
	new KeyboardPoller(this) .
        StartCommandRunner);
    mainLoopThread.IsBackground = true;		// So app terminates cleanly
    mainLoopThread.SetApartmentState (		// This is necessary to make
	ApartmentState.STA);			//  the clipboard work
    mainLoopThread.Start();			// Start the thread

    startupMacroFilename =			// If the file "waedit.mac"
        Application.StartupPath +		//  exists in the startup
        "\\waedit.mac";				//  directory, load it as a
    if (File.Exists(startupMacroFilename))	//  macro file
    {
	LoadMacroFile(startupMacroFilename);
    }   

    cursorBlinkTimer.Enabled = true;		// Start cursor blinking
}

/* ////////////////////////////////////////////////////////////////////////////
			     MainForm_FormClosed()
///////////////////////////////////////////////////////////////////////////////
DESCRIPTION:	The framework calls this function at shutdown after the form is
		closed.  We use it to perform various cleanup chores.

REVISIONS:	 9 Aug 16 - RAC - Genesis
//////////////////////////////////////////////////////////////////////////// */

private void MainForm_FormClosed(object sender, FormClosedEventArgs e)
{
    mainLoopThread.Abort();			// Kill the background thread
}						// End MainForm_FormClosed()

/* ////////////////////////////////////////////////////////////////////////////
			    MainForm_FormClosing()
///////////////////////////////////////////////////////////////////////////////
DESCRIPTION:	The framework calls this function as the app is shutting down,
		but before the main form is actually closed.  We use it to save
		the form's size, position, and state.

REVISIONS:	 1 Sep 16 - RAC - Copied from an internet example.
		 7 Sep 16 - RAC - Added bit to verify intent if changes to the
                 		   text haven't been saveed.
                 9 Oct 25 - RAC - Added call to close down the flowchart viewer
                                   pipe.
//////////////////////////////////////////////////////////////////////////// */

private void MainForm_FormClosing(object sender, FormClosingEventArgs e)
{
    if (text.HaveUnsavedChanges())
    {
        if (MessageBox.Show("Text modified.  Save changes?", "Waedit",
            MessageBoxButtons.YesNo, MessageBoxIcon.Question) ==
            DialogResult.Yes)
	{
	    e.Cancel = true;
	    return;
	}
    }

    Properties.Settings.Default.MainFormState = this.WindowState;
    if (this.WindowState==FormWindowState.Normal)
    {
        // save location and size if the state is normal
        Properties.Settings.Default.MainFormLocation = this.Location;
        Properties.Settings.Default.MainFormSize = this.Size;
    }
    else
    {
        // save the RestoreBounds if the form is minimized or maximized!
        Properties.Settings.Default.MainFormLocation = this.RestoreBounds.Location;
        Properties.Settings.Default.MainFormSize = this.RestoreBounds.Size;
    }

    // don't forget to save the settings
    Properties.Settings.Default.Save();
}						// End MainForm_FormClosing()

}						// End class MainForm
}						// End namespace waedit

